"""Cloud Storage uploads for the Asset Agent.

Both the Image and Video Asset agents use ``upload_to_gcs`` to publish
generated bytes to the public assets bucket. The bucket name is read
from ``GCS_ASSETS_BUCKET``; the bucket itself (uniform IAM, public-read,
90-day lifecycle) is provisioned via ``deploy/gcs_bucket.tf``.
"""

import logging
import os
from typing import Optional

from google.cloud import storage

logger = logging.getLogger(__name__)

UPLOAD_TIMEOUT_SECONDS = 60

_client_singleton: Optional[storage.Client] = None


def _client() -> storage.Client:
    """Lazily build a single Cloud Storage client."""
    global _client_singleton
    if _client_singleton is None:
        _client_singleton = storage.Client()
    return _client_singleton


def reset_client(client: Optional[storage.Client] = None) -> None:
    """Test/dev helper: replace or clear the module-level Cloud Storage client."""
    global _client_singleton
    _client_singleton = client


def upload_to_gcs(bytes_data: bytes, content_type: str, slug: str) -> str:
    """Upload bytes to the assets bucket and return a public URL.

    Args:
        bytes_data: The payload to upload.
        content_type: MIME type (e.g., ``"image/png"``, ``"video/mp4"``).
        slug: Object name within the bucket (e.g., ``"image-cover.png"``).

    Returns:
        Publicly reachable URL of the uploaded object.
    """
    bucket_name = _required_env("GCS_ASSETS_BUCKET")
    bucket = _client().bucket(bucket_name)
    blob = bucket.blob(slug)
    blob.upload_from_string(
        bytes_data, content_type=content_type, timeout=UPLOAD_TIMEOUT_SECONDS
    )
    return f"https://storage.googleapis.com/{bucket_name}/{slug}"


def _required_env(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        raise RuntimeError(
            f"{name} is not set; required for GCS uploads"
        )
    return value
